version: '3.4'

services:
  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: .
      dockerfile: Modules/UserManagement.Api/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Modules/Identity.Api/Dockerfile

  web.ui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: user-management-web-ui
      dockerfile: Dockerfile

