version: '3.4'

services:
  users.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: users.db
    environment:
      - SA_PASSWORD=DevEnvPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1430:1433"

  usermanagement.api:
    build:
      dockerfile: Modules/UserManagement.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=users.db;Database=AuthDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
    ports:
      - "5001:8080"
    depends_on:
      - users.db

  authorization.api:
    build:
      dockerfile: Modules/Authorization.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=users.db;Database=AuthDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
    ports:
      - "5002:8080"
    depends_on:
      - users.db
