version: '3.4'

services:
  users.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: users.db
    environment:
      - SA_PASSWORD=DevEnvPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1430:1433"

  usermanagement.api:
    build:
      dockerfile: Modules/UserManagement.Api/Dockerfile
    container_name: usermanagement.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=users.db;Database=AuthDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ConnectionStrings__MasterSqlServer=Server=users.db;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:8080
    ports:
      - "5001:8080"
    depends_on:
      - users.db

  authorization.api:
    build:
      dockerfile: Modules/Authorization.Api/Dockerfile
    container_name: authorization.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=users.db;Database=AuthDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:8080
    ports:
      - "5002:8080"
    depends_on:
      - users.db

  web.ui:
    build:
      context: user-management-web-ui
      dockerfile: Dockerfile
      args:
        # URLs for the APIs
        VUE_APP_USER_MANAGEMENT_API_URL: http://localhost:5001/users
    container_name: web.ui
    ports:
      - "8080:80"
    depends_on:
      - usermanagement.api
      - authorization.api
