version: '3.4'

services:
  users.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: users.db
    environment:
      - SA_PASSWORD=DevEnvPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1430:1433"

  usermanagement.api:
    build:
      context: .
      dockerfile: Modules/UserManagement.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: usermanagement.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=users.db;Database=AuthDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ConnectionStrings__MasterSqlServer=Server=users.db;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:8080
      - JwtSettings__SecretKey=Dev_Env_Supersecret_Very_Long_Key_2000
      - JwtSettings__Issuer=auth.api
      - JwtSettings__Audience=usermanagement
    ports:
      - "5001:8080"
    depends_on:
      - users.db

  identity.api:
    build:
      context: .
      dockerfile: Modules/Identity.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=users.db;Database=AuthDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:8080
      - JwtSettings__SecretKey=Dev_Env_Supersecret_Very_Long_Key_2000
      - JwtSettings__Issuer=auth.api
      - JwtSettings__Audience=usermanagement
    ports:
      - "5002:8080"
    depends_on:
      - users.db

  web.ui:
    build:
      context: user-management-web-ui
      dockerfile: Dockerfile
      args:
        # URLs for the APIs
        VUE_APP_USER_MANAGEMENT_API_URL: http://localhost:5001
        VUE_APP_IDENTITY_API_URL: http://localhost:5002
    container_name: web.ui
    ports:
      - "8080:80"
    depends_on:
      - usermanagement.api
      - identity.api
